name: build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r VetClinic/requirements.txt
          pip install -r VetClinic/requirements-dev.txt

          pip install pytest pytest-cov

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=VetClinic --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: PSK-projekty
          projectKey: PSK-projekty_VetClinic
          token: ${{ secrets.SONAR_TOKEN }}
