name: build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r VetClinic/requirements.txt
          pip install -r VetClinic/requirements-dev.txt
          pip install pytest pytest-cov

      - name: Run tests and generate coverage report
        run: |
          export PYTHONPATH=$PYTHONPATH:./VetClinic/API
          pytest --cov=VetClinic --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=PSK-projekty_VetClinic
            -Dsonar.organization=PSK-projekty
            -Dsonar.sources=VetClinic/API
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
